name: Blog's Docker Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the blog image
      run: docker build -f ./Dockerfile.onbuild -t linkxsystem/site:onbuild .
    # - name: Build the blog image (latest )
    #   run: docker build -t linkxsystem/site:latest .
